# Generated by Django 5.1.3 on 2024-11-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_registro',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='historial_rentas',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='detalles_membresia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
