# Generated by Django 5.1.4 on 2025-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_correo_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
