# Generated by Django 5.1.3 on 2024-12-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='ventas_totales',
            field=models.IntegerField(default=0),
        ),
    ]
