# Generated by Django 5.1.3 on 2024-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='Desconocido', max_length=25),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descuento',
            field=models.IntegerField(default=0, help_text='Descuento en porcentaje'),
        ),
    ]
