# Generated by Django 5.1.3 on 2024-11-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
