# Generated by Django 5.1.4 on 2025-01-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_ventas_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='vistas',
            field=models.IntegerField(default=0, help_text='Número de vistas'),
        ),
    ]
