# Generated by Django 5.1.3 on 2024-12-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descuento',
            field=models.IntegerField(default=0, help_text='Descuento en porcentaje'),
        ),
    ]
