# Generated by Django 5.1.3 on 2024-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_pelicula_director_alter_pelicula_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='categorias',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categorias',
            field=models.ManyToManyField(help_text='categorias de la pelicula', to='peliculas.categoriapel'),
        ),
    ]
